In [2]:
import pandas as pd
import numpy as np
from io import StringIO

In [3]:
train1 = np.genfromtxt(fname='../data/dataset1/train.txt')
train2 = np.genfromtxt(fname= '../data/dataset2/train.txt')
train3 = np.genfromtxt(fname='../data/dataset3/train.txt')
train4 = np.genfromtxt(fname='../data/dataset4/train.txt')
train5 = np.genfromtxt(fname='../data/dataset5/train.txt')

test1 = np.genfromtxt(fname='../data/dataset1/test.txt')
test2 = np.genfromtxt(fname='../data/dataset2/test.txt')
test3 = np.genfromtxt(fname='../data/dataset3/test.txt')
test4 = np.genfromtxt(fname='../data/dataset4/test.txt')
test5 = np.genfromtxt(fname='../data/dataset5/test.txt')

In [4]:
train1_df = pd.DataFrame(train1)
train2_df = pd.DataFrame(train2)
train3_df = pd.DataFrame(train3)
train4_df = pd.DataFrame(train4)
train5_df = pd.DataFrame(train5)

train1_df = train1_df.rename(columns={0: 'Label'})
train2_df = train2_df.rename(columns={0: 'Label'})
train3_df = train3_df.rename(columns={0: 'Label'})
train4_df = train4_df.rename(columns={0: 'Label'})
train5_df = train5_df.rename(columns={0: 'Label'})

test1_df = pd.DataFrame(test1)
test2_df = pd.DataFrame(test2)
test3_df = pd.DataFrame(test3)
test4_df = pd.DataFrame(test4)
test5_df = pd.DataFrame(test5)

test1_df = test1_df.rename(columns={0: 'Label'})
test2_df = test2_df.rename(columns={0: 'Label'})
test3_df = test3_df.rename(columns={0: 'Label'})
test4_df = test4_df.rename(columns={0: 'Label'})
test5_df = test5_df.rename(columns={0: 'Label'})

print train1_df['Label'].unique() #1, 2, 3
print train2_df['Label'].unique() # 1 to 7
print train3_df['Label'].unique() # 1 to 6
print train4_df['Label'].unique() #1 to 15
print train5_df['Label'].unique() # 1 and -1


[ 1.  3.  2.]
[ 7.  4.  6.  2.  5.  1.  3.]
[ 6.  5.  2.  1.  3.  4.]
[  4.  11.  13.   8.   3.  14.   9.   5.   6.   2.  12.  10.   7.   1.  15.]
[ 1. -1.]


In [13]:
from scipy.spatial.distance import euclidean

# Works directly with DataFrames
def similarity_matrix_euclidean(train_df, test_df):
    train = train_df.ix[:, 1:]
    test = test_df.ix[:, 1:]

    test_array = np.array(test)
    train_array = np.array(train)

    m, n = test_array.shape
    a, b = train_array.shape
    
    print m,n
    print a,b 

    similarity_matrix = np.zeros((m, a))

    for i in range(len(test_array)):
        for j in range(len(train_array)):
            similarity_matrix[i][j] = euclidean(test_array[i], train_array[j])
    sim_df = pd.DataFrame(similarity_matrix)
    return sim_df

sim_df = similarity_matrix_euclidean(train1_df, test1_df)
sim2_df = similarity_matrix_euclidean(train2_df, test2_df)

sim2_df

900 128
30 128
175 463
175 463


0          1          2          3          4          5    \
0     5.548925   6.308155   4.510574   4.860241   5.500027   6.635202   
1     3.279210   6.543144   3.495327   6.434711   2.928925   5.535486   
2     4.078955   4.155626   5.130584   4.376269   4.478646   3.613626   
3     3.529833   7.624276   4.054089   7.111435   2.924060   5.768879   
4     6.343577   3.517080   6.545167   4.094609   6.891790   6.870658   
5     5.590425   8.134296   5.637543   7.511995   5.215057   6.248062   
6     2.024400   4.698539   3.393090   4.568869   2.723813   5.011458   
7     3.196953   5.818658   2.553537   5.194840   2.721739   5.441350   
8     7.706049  10.436886   7.097104   9.701558   6.966397   8.850625   
9     5.314351   3.716592   6.645658   4.513139   5.890867   4.459071   
10    6.687453   9.814357   5.824491   9.185715   5.943979   8.095675   
11    4.461397   5.049740   6.305223   5.235089   4.995653   1.047820   
12    6.993994  10.273869   6.863271   9.609266   6.357131   8.461770   
13    2.071053   4.430998   3.094281   4.537189   2.690734   5.286120   
14    5.160480   4.230572   4.929656   2.752146   5.491732   5.286156   
15    4.543097   5.356974   2.926119   4.544515   4.461997   6.825065   
16    7.225255  10.675875   7.178096   9.954679   6.649812   8.170274   
17    3.038234   4.644823   2.925606   3.909414   3.132881   4.979555   
18   10.420002   7.471949  11.109558   8.203932  10.780914  10.032873   
19   10.153926   7.404509  11.030924   8.325384  10.530696   9.575563   
20    4.901434   8.113386   4.912453   7.623193   4.307461   5.978592   
21    3.991158   3.321853   5.412509   3.477739   4.814532   3.867768   
22    3.801651   6.278114   3.168661   5.672818   3.475596   6.626680   
23    8.061599   5.675881   8.151958   5.275039   8.511807   7.731455   
24    6.762183  10.198506   6.845836   9.596689   6.147663   7.980578   
25    3.040957   4.742812   4.109453   3.844229   3.615350   3.276621   
26    3.968300   5.752742   5.581466   5.459428   4.377559   1.852277   
27    3.756914   3.747072   2.950934   3.412106   4.064572   5.848515   
28    3.900332   3.954406   4.354020   2.534609   4.380360   4.473677   
29    2.320535   5.161654   3.462973   4.775804   2.847249   4.255861   
..         ...        ...        ...        ...        ...        ...   
145   2.303191   4.815793   3.102388   4.545538   2.843098   4.292079   
146   9.494979   6.740810   9.833757   6.863277   9.891129   8.449403   
147   6.088970   7.496688   5.045327   6.610836   5.819762   7.577610   
148   3.052510   5.911746   3.743794   5.170280   3.018183   4.450482   
149  16.493162  19.297101  16.293899  18.763514  15.725929  17.007558   
150   4.592837   4.963808   6.428959   5.084100   5.100883   2.400195   
151   5.126123   8.508731   4.904822   8.027592   4.426744   7.344041   
152   6.438823   5.035173   6.023685   3.880361   6.752928   6.579161   
153   6.357310   9.213752   5.858779   8.514247   5.648641   8.478778   
154   3.502356   4.216186   4.287284   3.832106   4.154498   5.565980   
155   4.840312   7.666676   4.786017   6.756581   4.553510   5.549561   
156   4.838031   7.879505   4.534038   7.072337   4.476531   6.505345   
157   4.056924   4.103529   4.084817   4.587039   4.247220   5.147873   
158   8.851871  12.012619   8.841566  11.264961   8.173553   9.340220   
159   4.811136   4.634933   6.120454   4.993032   5.229923   3.328914   
160   6.563491   9.479864   6.839002   8.724178   6.319016   6.656930   
161   7.196521   9.302371   7.100481   8.560470   6.904613   8.376370   
162   2.388493   4.611163   3.027146   4.127319   2.995870   4.494913   
163   7.161548   6.665958   7.157289   5.395225   7.478857   7.518922   
164   6.425693  10.050533   6.844727   9.117522   5.935539   7.039753   
165   7.861121   5.400357   9.266713   6.568520   8.398324   5.601933   
166   7.777161   5.561104   7.915958   4.977367   8.246201   7.625631   
167   9.719789  12.519217  10.190243  11.880756   9.312155   8.893114

In [14]:
def get_review(train_case):
    return train1_df.iloc[train_case].Label

def nearest_neighbours(similarity_matrix, k):
    neighbours = pd.DataFrame(similarity_matrix.apply(lambda s: s.nsmallest(k).index.tolist(), axis =1))
    neighbours = neighbours.rename(columns={0:'nbr_list'})
    neighbours['test_case_id'] = neighbours.index.values

    # getting the scores of each train neighbour from the train dataframe
    nbr_scores = []

    # creating a list of lists containing the sentiment scores for each set of train neighbours
    # [0, 1, 2, 3, 4] -> [1, 1, 1, 1, 1] from train data set

    test_scores_ref = []

    for i in range(neighbours.shape[0]): #row
        for j in range(len(neighbours['nbr_list'].iloc[i])):  #element
            a = neighbours['nbr_list'].iloc[i][j]
            nbr_scores.append(get_review(int(a)))

    test_scores_ref = [nbr_scores[i:i+k] for i in range(0, len(nbr_scores), k)]
    test_scores_series = pd.DataFrame(test_scores_ref)
    
    test_scores_series['Label1'] = test_scores_series.apply(lambda y: y.value_counts(), axis=1)[1]
    test_scores_series['Label2'] = test_scores_series.apply(lambda y: y.value_counts(), axis=1)[2]
    test_scores_series['Label3'] = test_scores_series.apply(lambda y: y.value_counts(), axis=1)[3]
    
    test_scores_series['Label1'].fillna(0, inplace=True)
    test_scores_series['Label2'].fillna(0, inplace=True)
    test_scores_series['Label3'].fillna(0, inplace=True)

    # determining conditions for majority vote of nearest neighbours
    test_scores_series['MajVote'] = test_scores_series[['Label1','Label2','Label3']].idxmax(axis=1)
    
    # choices to be printed are 1, 2 and 3
    choices = ["1", "2", "3"]
    conditions = [test_scores_series['MajVote']=='Label1',
                  test_scores_series['MajVote']=='Label2',
                  test_scores_series['MajVote']=='Label3']
    test_scores_series['Answer'] = np.select(conditions, choices)
    return test_scores_series
    
def write_submission_file(test_scores_series, k):
    test_scores_series.to_csv(str.format('submission_{}.txt',k), sep='\n', mode ='a',columns=[0], header=False, index=False)
    
    

In [1]:
from sklearn.metrics import accuracy_score
y_true = test2_df['Label']
y_pred = nearest_neighbours(sim2_df, 3)

NameError: name 'test2_df' is not defined