In [4]:
import numpy as np

x = np.full((10,10), -1)
x[3, 4] = 9


/home/bhavika/anaconda2/lib/python2.7/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((10, 10), -1) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [6]:
print x

print x[3,4]

[[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1.  9. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]
9.0


In [10]:
import pandas as pd

train1 = np.genfromtxt(fname='../data/dataset1/train.txt')
train1_df = pd.DataFrame(train1)
train1_df = train1_df.rename(columns={0: 'Label'})

choices = train1_df['Label'].unique()

print choices
print type(choices)

[ 1.  3.  2.]
<type 'numpy.ndarray'>


In [15]:
train1 = np.genfromtxt(fname='../data/dataset1/train.txt')
train2 = np.genfromtxt(fname= '../data/dataset2/train.txt')
train3 = np.genfromtxt(fname='../data/dataset3/train.txt')
train4 = np.genfromtxt(fname='../data/dataset4/train.txt')
train5 = np.genfromtxt(fname='../data/dataset5/train.txt')

test1 = np.genfromtxt(fname='../data/dataset1/test.txt')
test2 = np.genfromtxt(fname='../data/dataset2/test.txt')
test3 = np.genfromtxt(fname='../data/dataset3/test.txt')
test4 = np.genfromtxt(fname='../data/dataset4/test.txt')
test5 = np.genfromtxt(fname='../data/dataset5/test.txt')

train1_df = pd.DataFrame(train1)
train2_df = pd.DataFrame(train2)
train3_df = pd.DataFrame(train3)
train4_df = pd.DataFrame(train4)
train5_df = pd.DataFrame(train5)

train1_df = train1_df.rename(columns={0: 'Label'})
train2_df = train2_df.rename(columns={0: 'Label'})
train3_df = train3_df.rename(columns={0: 'Label'})
train4_df = train4_df.rename(columns={0: 'Label'})
train5_df = train5_df.rename(columns={0: 'Label'})

test1_df = pd.DataFrame(test1)
test2_df = pd.DataFrame(test2)
test3_df = pd.DataFrame(test3)
test4_df = pd.DataFrame(test4)
test5_df = pd.DataFrame(test5)

test1_df = test1_df.rename(columns={0: 'Label'})
test2_df = test2_df.rename(columns={0: 'Label'})
test3_df = test3_df.rename(columns={0: 'Label'})
test4_df = test4_df.rename(columns={0: 'Label'})
test5_df = test5_df.rename(columns={0: 'Label'})





In [16]:
train = [train1, train2, train3, train4, train5]
test = [test1, test2, test3, test4, test5]

for i in range(len(train)):
    m, n = train[i].shape
    print m,n 
    print "Time series length for dataset",i, n

30 129
Time series length for dataset 0 129
175 464
Time series length for dataset 1 464
200 428
Time series length for dataset 2 428
500 129
Time series length for dataset 3 129
1000 153
Time series length for dataset 4 153


In [23]:
bhavika = np.zeros((2,3))

bhavika[0, 2] = 1
bhavika[0, 1] = 1
bhavika[1, 0] = 2
bhavika[1, 1] = 1

bt = pd.DataFrame(bhavika)

choices = [1, 2]

for i in range(len(choices)):
    bt['Choice{}'.format(i+1)] = bt.apply(lambda y: y.value_counts(), axis=1)[choices[i]]
    
print bt

     0    1    2  Choice1  Choice2
0  0.0  1.0  1.0      2.0        1
1  2.0  1.0  0.0      1.0        1


In [58]:
from numpy import array, zeros, argmin, inf, equal
from scipy.spatial.distance import cdist

def fastdtw(x, y, dist):
    """
    Computes Dynamic Time Warping (DTW) of two sequences in a faster way.
    Instead of iterating through each element and calculating each distance,
    this uses the cdist function from scipy (https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html)
    :param array x: N1*M array
    :param array y: N2*M array
    :param string or func dist: distance parameter for cdist. When string is given, cdist uses optimized functions for the distance metrics.
    If a string is passed, the distance function can be 'braycurtis', 'canberra', 'chebyshev', 'cityblock', 'correlation', 'cosine', 'dice', 'euclidean', 'hamming', 'jaccard', 'kulsinski', 'mahalanobis', 'matching', 'minkowski', 'rogerstanimoto', 'russellrao', 'seuclidean', 'sokalmichener', 'sokalsneath', 'sqeuclidean', 'wminkowski', 'yule'.
    Returns the minimum distance, the cost matrix, the accumulated cost matrix, and the wrap path.
    """
    assert len(x)
    assert len(y)
    r, c = len(x), len(y)
    
    print r, c
    
    D0 = zeros((r + 1, c + 1))
    
    # sets all boundaries (wallside) rows to inf - 1 represents "start from pos 1"
    D0[0, 1:] = inf
    D0[1:, 0] = inf
  
    print D0
    
    # this extracts the part below the inf boundaries - all zero space
    D1 = D0[1:, 1:]
    
    print D1
    
    D0[1:,1:] = cdist(x,y,dist)
    print D0[1:, 1:]
    
    C = D1.copy()
    for i in range(r):
        for j in range(c):
            D1[i, j] += min(D0[i, j], D0[i, j+1], D0[i+1, j])
    print D1[-1, -1]
    print sum(D1.shape)
    return D1[-1, -1] / sum(D1.shape)

In [59]:

x = [[3, 2, 1, 2, 3, 3, 3], 
     [3, 2, 1, 2, 4, 6, 7],
    [3, 2, 1, 2, 4, 6, 7]]
y = [[1, 1, 2, 3, 4, 3, 2], 
     [1, 3, 4, 6, 2, 1, 3],
    [1, 3, 4, 6, 2, 1, 3]]

dist = fastdtw(x, y, 'euclidean')

print dist



3 3
[[  0.  inf  inf  inf]
 [ inf   0.   0.   0.]
 [ inf   0.   0.   0.]
 [ inf   0.   0.   0.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 3.          5.91607978  5.91607978]
 [ 6.40312424  8.66025404  8.66025404]
 [ 6.40312424  8.66025404  8.66025404]]
20.3205080757
6
3.38675134595
